# Name: 13682_create_edit_sp
# Target: windows
##
MyConnect({"user":"root","host":"localhost"})

MyQuery("DROP PROCEDURE IF EXISTS test.p1")
MyQuery("DROP PROCEDURE IF EXISTS test.testproc1")
MyQuery("CREATE PROCEDURE test.p1()\nBEGIN\n  SELECT 1;\nEND")

#MouseRelease((-793, 369), button=1)
#ClickObject(PATH("ConnectToInstanceForm.ConnectToHostPnl"), offset=(29, 82))
#Delay(1)
#Key(Return)
#Delay(2)

ClickObject(PATH("MainForm.SidebarPnl.AdminTreeView"), offset=(66, 253))
Delay(2)
ClickObject(PATH("MainForm.SidebarPnl.SubTreePnl.CatalogSubTreePnl.SchemataFrame.CatalogVST"), offset=(32, 46))
Delay(1)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl"), offset=(265, 14))
Delay(3)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl.StoredProcTabSheet.Panel10.Panel11.AddSPBtn"), offset=(48, 9))
Delay(1)
Type('testproc1')
Delay(1)
Key(Tab)
Key(Return)
Delay(1)
Type('select 1;')
ClickObject(PATH("EditorSqlForm.BottomPnl.ExecuteSQLBtn"))
Delay(3)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl.StoredProcTabSheet.StoredProcsVST"), offset=(29, 23))
Delay(3)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl.StoredProcTabSheet.Panel10.Panel11.EditSPBtn"), offset=(46, 12))
Delay(2)
ClickObject(PATH("EditorSqlForm.SqlUCE"), offset=(103, 32))
Delay(6)
Type('1')
ClickObject(PATH("EditorSqlForm.BottomPnl.ExecuteSQLBtn"))
Delay(2)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl.StoredProcTabSheet.Panel10.Panel11.RefreshSPBtn"), offset=(42, 13))

CheckDBQuery("select count(*) from information_schema.routines where SPECIFIC_NAME = 'testproc1'", [[1]]) 
MyQuery("drop procedure test.testproc1") 
MyQuery("drop procedure test.p1") 
