# Name: 16114_sp_edit_schema_retain
# Target: windows
##

MyConnect({"user":"root","host":"localhost"})
MyQuery("drop procedure if exists test.testproc1")
MyQuery("drop procedure if exists test.testproc11")  

#Delay(1)
#ClickObject(PATH("ConnectToInstanceForm.ConnectToHostPnl"), offset=(86, 60))
#Delay(2)
#Key(Return)
#Delay(2)

ClickObject(PATH("MainForm.SidebarPnl.AdminTreeView"), offset=(61, 254))
Delay(2)
ClickObject(PATH("MainForm.SidebarPnl.SubTreePnl.CatalogSubTreePnl.SchemataFrame.CatalogVST"), offset=(29, 46))
Delay(2)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl"), offset=(234, 11))
Delay(5)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl.StoredProcTabSheet.Panel10.Panel11.AddSPBtn"), offset=(48, 14))
Delay(2)
Type('testproc1')
Delay(1)
Key(Return)
Delay(2)
Type('select 1;')
ClickObject(PATH("EditorSqlForm.BottomPnl.ExecuteSQLBtn"), offset=(8, 11))
Delay(2)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl.StoredProcTabSheet.StoredProcsVST"), offset=(102, 29))
Delay(2)
ClickObject(PATH("MainForm.DockPnl.CatalogPnl.CatalogPageControl.SchemaSheet.SchemaPageControl.StoredProcTabSheet.Panel10.Panel11.EditSPBtn"), offset=(61, 11))
Delay(7)
ClickObject(PATH("EditorSqlForm.SqlUCE"), offset=(104, 31))
Delay(2)
ClickObject(PATH("EditorSqlForm.SqlUCE"), offset=(410, 6))
Delay(2)
Type('1')
ClickObject(PATH("EditorSqlForm.BottomPnl.ExecuteSQLBtn"), offset=(8, 16))
Delay(2)

CheckDBQuery("select count(*) from information_schema.routines where SPECIFIC_NAME = 'testproc1'", [[0]]) 
CheckDBQuery("select count(*) from information_schema.routines where SPECIFIC_NAME = 'testproc11'", [[1]]) 
MyQuery("drop procedure test.testproc11") 
CheckDBQuery("select count(*) from information_schema.routines where SPECIFIC_NAME = 'testproc11'", [[0]]) 
